#!/usr/bin/env ruby

require_relative "./../lib/movie_ticket"

query = ARGV.join(" ")

# get torrent
results = MovieTicket::TorrentAPI.new.search(query)
magnet_link = results.first["download"]
title = results.first["title"]
magnet_filename = File.join(ENV["WATCH_DIR"], "#{title}.magnet")
File.open(magnet_filename, "wb") do |file|
  file << magnet_link
  puts "Magnet file written to: #{magnet_filename}"
end

# get subtitles
results = nil
data = nil
MovieTicket::SubtitlesAPI.connection do |api|
  results = api.search(title)
  data = api.download(results.first["IDSubtitleFile"])
end

full_path = [ENV["DOWNLOAD_DIR"], results.first["SubFileName"]]
subtitles_filename = File.join(full_path)
subtitles = Base64.decode64(data)
gzip = Zlib::GzipReader.new(StringIO.new(subtitles))
File.open(subtitles_filename, "wb") do |file|
  file << gzip.read
  puts "Subtitles written to: #{subtitles_filename}"
end
